config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
 

  get "/authors", to: "authors#index"
  get "/authors/new", to: "authors#new"
  post "/authors", to: "authors#create"
  get "/authors/:id", to: "authors#show", as: 'author'
  get '/books', to: 'books#index'
  get '/books/:id', to: 'books#show'
  resources :books
  resources :authors do
    resources :books
  end
  

  # Defines the root path route ("/")
  # root "posts#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/author.rb
class Author < ApplicationRecord
  has_many :books
end

app/models/book.rb
class Book < ApplicationRecord
  belongs_to :author
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController
  def index
    @authors = Author.all
  end

  def show
    @author = Author.find(params[:id])
    
    @books = @author.books
  end

  def new 

  end

  def create
      @authors= Author.create(author_params)
      @authors.save
      
      redirect_to "/authors"
  end

  def author_params
    params.permit(:name, :deceased, :age)
  end
end

app/controllers/books_controller.rb
class BooksController < ApplicationController
  def index
    @books = Book.all
  end

  def show
    @book = Book.find(params[:id])
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/authors/index.html.erb
<nav>
  <ul>
    <li><%= link_to "Authors", authors_path %></li>
    <li><%= link_to "Books", books_path %></li>
  </ul>
</nav>
  <%= link_to "New Author", new_author_path %>

<% if @authors.any? %>
  <h1>Authors List</h1>
  <ul>
    <% @authors.each do |author| %>
      <li>
        <p><strong>Name:</strong> <%= author.name %></p>
        <p><strong>Deceased:</strong> <%= author.deceased%></p>
        <p><strong>Age:</strong> <%= author.age %></p>
        <p><strong>Created at:</strong> <%= author.created_at %></p>
        <p><strong>Updated at:</strong> <%= author.updated_at %></p>
        <%= link_to "View Books", author_books_path(author) %>
      </li>
    <% end %>
  </ul>
<% end %>

app/views/authors/new.html.erb
<h1>New Author</h1>

<%= form_with model: @author, url: authors_path, local: true do |form| %>
  <div>
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>
  <div>
    <%= form.label :deceased %>
    <%= form.check_box :deceased %>
  </div>
  <div>
    <%= form.label :age %>
    <%= form.number_field :age %>
  </div>
  <div>
    <%= form.submit "Create Author" %>
  </div>
<% end %>

app/views/authors/show.html.erb
<nav>
  <%= link_to "Books", books_path %>
</nav>

<h1>Author Details</h1>
<p><strong>Name:</strong> <%= @author.name %></p>
<p><strong>Deceased:</strong> <%= @author.deceased ? 'Yes' : 'No' %></p>
<p><strong>Age:</strong> <%= @author.age %></p>

<% if @books.any? %>
  <h2>Books by <%= @author.name %> :</h2>
  <ul>
    <% @books.each do |book| %>
      <li>
        <h3><%= book.title %></h3>
        <p><strong>Genre:</strong> <%= book.genre %></p>
        <p><strong>Published:</strong> <%= book.is_published? ? 'Yes' : 'No' %></p>
        <p><strong>Publication Year:</strong> <%= book.publication_year %></p>
      </li>
    <% end %>
  </ul>
  <p><strong>Total Books:</strong> <%= @books.count %></p>

<% end %>

app/views/books/index.html.erb
<nav>
  <ul>
    <li><%= link_to "Authors", authors_path %></li>
    <li><%= link_to "Books", books_path %></li>
  </ul>
</nav>
<ul>
  <% @books.each do |book| %>
    <li><%= book.title %></li>
    <li><%= book.genre %></li>
    <li><%= book.is_published %></li>
    <li><%= book.publication_year %></li>
  <% end %>
</ul>

app/views/books/show.html.erb
<nav>
  <%= link_to "books", books_path %>
</nav>
<h1><%= @book.title %></h1>
<p><strong>Genre:<strong> <%= @book.genre %></p>
<p><strong>Published:</strong> <%= @book.is_published ? 'Yes' : 'No' %></p>
<p><strong>Publication Year:</strong> <%= @book.publication_year %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RelationalRailsProject</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>